### ISSUE TITLE
opposite of this

### ISSUE THREAD

**Issue by eadmaster** [lycantropos/cppstd#1]
do you know if there is any project that attempts the opposite of this?
(porting python stdlib to C++)

I've made an attempt here myself for educational purposes:
https://gist.github.com/eadmaster/8a42f9bbc653665ba187ec549aa9f1df

**Comment by lycantropos** [comment]
good day @eadmaster, some time ago I started [cppbuiltins](https://github.com/lycantropos/cppbuiltins) project, you can probably start from there, but I don't know about any other, especially feature-complete version
